/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest2_Jin */

#ifndef _Included_com_zoeas_util_CalculateC
#define _Included_com_zoeas_util_CalculateC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest2_Jin
 * Method:    sendData
 * Signature: (DD)V
 */
JNIEXPORT jdouble JNICALL Java_com_zoeas_util_CalculateC_getData
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_example_jnitest2_Jin
 * Method:    getData
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_zoeas_util_CalculateC_setData
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
